[package]
name = "tui"
version = "0.1.0"
authors = ["Giles Hutton <hutton.giles@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tui = "0.14.0"
termion = "1.5.6"
unicode-width = "0.1.8"
sundbg = { path = "../../sundbg" }
