[package]
name = "commands"
version = "0.1.0"
authors = ["Giles Hutton <hutton.giles@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
debug = { path = "../debug" }
clap = "3.0.0-beta.2"
log = "0.4.14"